version: "3.2"
services:
  php:
    build: './php/'
    container_name: php
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
  nginx:
    build: './nginx/'
    container_name: nginx
    depends_on:
      - php
    networks:
      - backend
    ports:
      - "8080:80"
    volumes:
      - ./public_html/:/var/www/src/public/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  mysql:
    image: mysql:5.6.40
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
networks:
  backend: