version: "3.2"

services:
#  db:
#    image: mysql:5.7
#    volumes:
#      - ./docker/mysql/data:/var/lib/mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: somewordpress
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wordpress
#      MYSQL_PASSWORD: wordpress
#  wordpress:
#    depends_on:
#      - db
#    image: wordpress:latest
#    ports:
#      - "8000:80"
#    restart: always
#    environment:
#      WORDPRESS_DB_HOST: db:3306
#      WORDPRESS_DB_USER: wordpress
#      WORDPRESS_DB_PASSWORD: wordpress
#      WORDPRESS_DB_NAME: wordpress
#    volumes:
#      - ./public_html:/var/www/html
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - "8080:80"
#    environment:
#      PMA_HOST: db
#      MYSQL_ROOT_PASSWORD: somewordpress

  wordpress:
    build:
      context: './docker/wordpress/'
      dockerfile: 'Dockerfile'
    depends_on:
      - mysql
    container_name: wordpress
    ports:
      - "80:80"
    restart: always
    networks:
      - backend
    environment:
      XDEBUG_CONFIG: "remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: true
    volumes:
      - ./public_html:/var/www/html
      - ./docker/wordpress/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  mysql:
    build:
      context: './docker/mysql/'
      dockerfile: 'Dockerfile'
    container_name: mysql
    restart: always
    networks:
      - backend
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:delegated
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    build:
      context: './docker/phpmyadmin/'
      dockerfile: 'Dockerfile'
    container_name: phpmyadmin
    restart: always
    networks:
      - backend
    depends_on:
      - mysql
    ports:
      - "${PHPMYADMIN_HOST_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql

networks:
  backend:
    driver: bridge