version: "3.2"

services:

  php:
    build:
      context: './docker/php/'
      dockerfile: 'Dockerfile'
      args:
        PHP_VERSION_DOCKERFILE: ${PHP_VERSION}
    container_name: php
    depends_on:
      - mysql
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/

  nginx:
    build: './docker/nginx/'
    container_name: nginx
    depends_on:
      - php
    networks:
      - backend
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
      - ./docker/nginx/log/nginx-access.log:/var/log/nginx/access.log
      - ./docker/nginx/log/nginx-error.log:/var/log/nginx/error.log
      - ./public_html/:/var/www/html/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  mysql:
    build:
      context: './docker/mysql/'
      dockerfile: 'Dockerfile'
      args:
        MYSQL_VERSION_DOCKERFILE: ${MYSQL_VERSION}
    container_name: mysql
    networks:
      - backend
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=sait
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

networks:
  backend:
    driver: bridge