version: "3.2"
services:
  app:
    build:
      context: './docker/app/'
      dockerfile: 'Dockerfile'
      args:
        OS: ${DOCKER_OS}
        OS_VERSION: ${OS_VERSION}
        PHP_VERSION_DOCKERFILE: ${PHP_VERSION}
    container_name: app
    networks:
      - backend
#  mysql:
#    image: mysql:5.6.40
#    networks:
#      - backend
#    environment:
#      - MYSQL_ROOT_PASSWORD=rootpassword
networks:
  backend: