version: "3.2"

services:

  php:
    build:
      context: './docker/php/'
      dockerfile: 'Dockerfile'
      args:
        PHP_VERSION_DOCKERFILE: ${PHP_VERSION}
    container_name: php
    networks:
      - backend
    depends_on:
      - mysql
    volumes:
      - ./public_html/:/var/www/html/
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  nginx:
    build:
      context: './docker/nginx/'
      dockerfile: 'Dockerfile'
    container_name: nginx
    networks:
      - backend
    depends_on:
      - php
    ports:
      - "${NGINX_HOST_PORT}:80"
    volumes:
      - ./docker/nginx/log/nginx-access.log:/var/log/nginx/access.log
      - ./docker/nginx/log/nginx-error.log:/var/log/nginx/error.log
      - ./public_html/:/var/www/html/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/

  mysql:
    build:
      context: './docker/mysql/'
      dockerfile: 'Dockerfile'
      args:
        MYSQL_VERSION_DOCKERFILE: ${MYSQL_VERSION}
    container_name: mysql
    networks:
      - backend
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    build:
      context: './docker/phpmyadmin/'
      dockerfile: 'Dockerfile'
    container_name: phpmyadmin
    networks:
      - backend
    depends_on:
      - mysql
    ports:
      - "${PHPMYADMIN_HOST_PORT}:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql

networks:
  backend:
    driver: bridge